// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.3
// source: api.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoneNestRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *MsgA `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *LoneNestRequest) Reset() {
	*x = LoneNestRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoneNestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoneNestRequest) ProtoMessage() {}

func (x *LoneNestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoneNestRequest.ProtoReflect.Descriptor instead.
func (*LoneNestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoneNestRequest) GetA() *MsgA {
	if x != nil {
		return x.A
	}
	return nil
}

type LoneNestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B *MsgB `protobuf:"bytes,1,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *LoneNestResponse) Reset() {
	*x = LoneNestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoneNestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoneNestResponse) ProtoMessage() {}

func (x *LoneNestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoneNestResponse.ProtoReflect.Descriptor instead.
func (*LoneNestResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoneNestResponse) GetB() *MsgB {
	if x != nil {
		return x.B
	}
	return nil
}

type SeveralParamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B *MsgA  `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C *MsgC  `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	D int64  `protobuf:"varint,4,opt,name=d,proto3" json:"d,omitempty"`
}

func (x *SeveralParamsRequest) Reset() {
	*x = SeveralParamsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeveralParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeveralParamsRequest) ProtoMessage() {}

func (x *SeveralParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeveralParamsRequest.ProtoReflect.Descriptor instead.
func (*SeveralParamsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *SeveralParamsRequest) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *SeveralParamsRequest) GetB() *MsgA {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *SeveralParamsRequest) GetC() *MsgC {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *SeveralParamsRequest) GetD() int64 {
	if x != nil {
		return x.D
	}
	return 0
}

type SeveralParamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *MsgA `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B *MsgB `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *SeveralParamsResponse) Reset() {
	*x = SeveralParamsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeveralParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeveralParamsResponse) ProtoMessage() {}

func (x *SeveralParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeveralParamsResponse.ProtoReflect.Descriptor instead.
func (*SeveralParamsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *SeveralParamsResponse) GetA() *MsgA {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *SeveralParamsResponse) GetB() *MsgB {
	if x != nil {
		return x.B
	}
	return nil
}

type MultiDepthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *MsgD `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *MultiDepthRequest) Reset() {
	*x = MultiDepthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiDepthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiDepthRequest) ProtoMessage() {}

func (x *MultiDepthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiDepthRequest.ProtoReflect.Descriptor instead.
func (*MultiDepthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *MultiDepthRequest) GetA() *MsgD {
	if x != nil {
		return x.A
	}
	return nil
}

type MultiDepthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *MsgE `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *MultiDepthResponse) Reset() {
	*x = MultiDepthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiDepthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiDepthResponse) ProtoMessage() {}

func (x *MultiDepthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiDepthResponse.ProtoReflect.Descriptor instead.
func (*MultiDepthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *MultiDepthResponse) GetA() *MsgE {
	if x != nil {
		return x.A
	}
	return nil
}

type MsgA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A string `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
}

func (x *MsgA) Reset() {
	*x = MsgA{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgA) ProtoMessage() {}

func (x *MsgA) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgA.ProtoReflect.Descriptor instead.
func (*MsgA) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *MsgA) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

type MsgB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	B int64 `protobuf:"varint,1,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *MsgB) Reset() {
	*x = MsgB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgB) ProtoMessage() {}

func (x *MsgB) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgB.ProtoReflect.Descriptor instead.
func (*MsgB) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *MsgB) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type MsgC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C bool `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *MsgC) Reset() {
	*x = MsgC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgC) ProtoMessage() {}

func (x *MsgC) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgC.ProtoReflect.Descriptor instead.
func (*MsgC) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *MsgC) GetC() bool {
	if x != nil {
		return x.C
	}
	return false
}

type MsgD struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A *MsgA `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B *MsgB `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *MsgD) Reset() {
	*x = MsgD{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgD) ProtoMessage() {}

func (x *MsgD) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgD.ProtoReflect.Descriptor instead.
func (*MsgD) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *MsgD) GetA() *MsgA {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *MsgD) GetB() *MsgB {
	if x != nil {
		return x.B
	}
	return nil
}

type MsgE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C *MsgC `protobuf:"bytes,1,opt,name=c,proto3" json:"c,omitempty"`
	D *MsgD `protobuf:"bytes,2,opt,name=d,proto3" json:"d,omitempty"`
}

func (x *MsgE) Reset() {
	*x = MsgE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgE) ProtoMessage() {}

func (x *MsgE) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgE.ProtoReflect.Descriptor instead.
func (*MsgE) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *MsgE) GetC() *MsgC {
	if x != nil {
		return x.C
	}
	return nil
}

func (x *MsgE) GetD() *MsgD {
	if x != nil {
		return x.D
	}
	return nil
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x29, 0x0a, 0x0f, 0x4c, 0x6f, 0x6e, 0x65, 0x4e, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e,
	0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x41, 0x52, 0x01, 0x61, 0x22, 0x2a, 0x0a, 0x10, 0x4c, 0x6f,
	0x6e, 0x65, 0x4e, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x01, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d,
	0x73, 0x67, 0x42, 0x52, 0x01, 0x62, 0x22, 0x62, 0x0a, 0x14, 0x53, 0x65, 0x76, 0x65, 0x72, 0x61,
	0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c,
	0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x61, 0x12, 0x16, 0x0a, 0x01,
	0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67,
	0x41, 0x52, 0x01, 0x62, 0x12, 0x16, 0x0a, 0x01, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x43, 0x52, 0x01, 0x63, 0x12, 0x0c, 0x0a, 0x01,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x64, 0x22, 0x47, 0x0a, 0x15, 0x53, 0x65,
	0x76, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08,
	0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x41, 0x52, 0x01, 0x61, 0x12, 0x16, 0x0a, 0x01, 0x62,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x42,
	0x52, 0x01, 0x62, 0x22, 0x2b, 0x0a, 0x11, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x65, 0x70, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x44, 0x52, 0x01, 0x61,
	0x22, 0x2c, 0x0a, 0x12, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x45, 0x52, 0x01, 0x61, 0x22, 0x14,
	0x0a, 0x04, 0x4d, 0x73, 0x67, 0x41, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x01, 0x61, 0x22, 0x14, 0x0a, 0x04, 0x4d, 0x73, 0x67, 0x42, 0x12, 0x0c, 0x0a, 0x01,
	0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x62, 0x22, 0x14, 0x0a, 0x04, 0x4d, 0x73,
	0x67, 0x43, 0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x01, 0x63,
	0x22, 0x36, 0x0a, 0x04, 0x4d, 0x73, 0x67, 0x44, 0x12, 0x16, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x41, 0x52, 0x01, 0x61,
	0x12, 0x16, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x73, 0x67, 0x42, 0x52, 0x01, 0x62, 0x22, 0x36, 0x0a, 0x04, 0x4d, 0x73, 0x67, 0x45,
	0x12, 0x16, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62,
	0x2e, 0x4d, 0x73, 0x67, 0x43, 0x52, 0x01, 0x63, 0x12, 0x16, 0x0a, 0x01, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x73, 0x67, 0x44, 0x52, 0x01, 0x64,
	0x32, 0xc8, 0x01, 0x0a, 0x06, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x37, 0x0a, 0x08, 0x4c,
	0x6f, 0x6e, 0x65, 0x4e, 0x65, 0x73, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x6f, 0x6e,
	0x65, 0x4e, 0x65, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70,
	0x62, 0x2e, 0x4c, 0x6f, 0x6e, 0x65, 0x4e, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x53, 0x65, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x76, 0x65, 0x72,
	0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x76, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x65, 0x70, 0x74, 0x68, 0x12, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x65, 0x70, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x44, 0x65, 0x70, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x41, 0x5a, 0x3f, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x63, 0x6f, 0x64,
	0x65, 0x64, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x67, 0x65, 0x6e, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x6e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_proto_goTypes = []interface{}{
	(*LoneNestRequest)(nil),       // 0: pb.LoneNestRequest
	(*LoneNestResponse)(nil),      // 1: pb.LoneNestResponse
	(*SeveralParamsRequest)(nil),  // 2: pb.SeveralParamsRequest
	(*SeveralParamsResponse)(nil), // 3: pb.SeveralParamsResponse
	(*MultiDepthRequest)(nil),     // 4: pb.MultiDepthRequest
	(*MultiDepthResponse)(nil),    // 5: pb.MultiDepthResponse
	(*MsgA)(nil),                  // 6: pb.MsgA
	(*MsgB)(nil),                  // 7: pb.MsgB
	(*MsgC)(nil),                  // 8: pb.MsgC
	(*MsgD)(nil),                  // 9: pb.MsgD
	(*MsgE)(nil),                  // 10: pb.MsgE
}
var file_api_proto_depIdxs = []int32{
	6,  // 0: pb.LoneNestRequest.a:type_name -> pb.MsgA
	7,  // 1: pb.LoneNestResponse.b:type_name -> pb.MsgB
	6,  // 2: pb.SeveralParamsRequest.b:type_name -> pb.MsgA
	8,  // 3: pb.SeveralParamsRequest.c:type_name -> pb.MsgC
	6,  // 4: pb.SeveralParamsResponse.a:type_name -> pb.MsgA
	7,  // 5: pb.SeveralParamsResponse.b:type_name -> pb.MsgB
	9,  // 6: pb.MultiDepthRequest.a:type_name -> pb.MsgD
	10, // 7: pb.MultiDepthResponse.a:type_name -> pb.MsgE
	6,  // 8: pb.MsgD.a:type_name -> pb.MsgA
	7,  // 9: pb.MsgD.b:type_name -> pb.MsgB
	8,  // 10: pb.MsgE.c:type_name -> pb.MsgC
	9,  // 11: pb.MsgE.d:type_name -> pb.MsgD
	0,  // 12: pb.Nested.LoneNest:input_type -> pb.LoneNestRequest
	2,  // 13: pb.Nested.SeveralParams:input_type -> pb.SeveralParamsRequest
	4,  // 14: pb.Nested.MultiDepth:input_type -> pb.MultiDepthRequest
	1,  // 15: pb.Nested.LoneNest:output_type -> pb.LoneNestResponse
	3,  // 16: pb.Nested.SeveralParams:output_type -> pb.SeveralParamsResponse
	5,  // 17: pb.Nested.MultiDepth:output_type -> pb.MultiDepthResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoneNestRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoneNestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeveralParamsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeveralParamsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiDepthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiDepthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgD); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
